### ISSUE TITLE
下拉框样式有问题

### ISSUE THREAD

**Issue by ReAlign** [kaola-fed/nek-ui#145]
![image](https://user-images.githubusercontent.com/25849349/27790818-c57bfd8a-6024-11e7-9e07-a3b12277fabb.png)

**Comment by ziian-dev** [comment]
76937f341a3f320da3eeb4ad5479ed0c4462fa49  输入框样式fix

**Comment by nupthale** [comment]
优化样式命名， 防污染

**Comment by lllang** [comment]
高度本来就这么高的。因为上面是输入框。下面是已选的项。具体样式可以参考交互上的。
