### ISSUE TITLE
kl-select将空数据置为0

### ISSUE THREAD

**Issue by summercloud** [kaola-fed/nek-ui#150]
html代码
`<kl-select source=[{id:0,name:'aaa'},{id:1,name:'bbb'}] value={temp} />`
js代码
`temp = ''`
如果像上述情况，使用了kl-select组件以后，temp会被自动修改成为0。选框默认会选到id为0的项。

**Comment by lllang** [comment]
已验证，在 eslint 之后就没问题了。

**Comment by int64ago** [comment]
@lllang 看来是 `==` 的锅啊
