### ISSUE TITLE
【BugBash】上传组件收集到的问题优化

### ISSUE THREAD

**Issue by nupthale** [kaola-fed/nek-ui#160]
1. 加是否可以编辑状态属性，不显示上传按钮和删除按钮readonly
2. 预览图片改成一个独立的组件
3. 预览图片在mac下看不到关闭按钮
4. 图片上传的验证，参见validation
5. 图片上传最大数量默认不要限制
6. 图片上传的num-perline去掉，自动换行flex
7. 图片上传百分比有问题
8. 图片上传list-type为card的时候，浮层滚动，设置最大高度
9. 向外抛事件success/error, 将服务端的响应传出来
10. 图片上传浮层点击同一行无法收起
11. fileList不更新，增加watch
12. 图片上传宽高校验，宽高比例校验
13. 压缩文件rar直接显示文件后缀

**Comment by int64ago** [comment]
@llwanghong  另外目录结构需要调整下

子组件统一放到父组件目录下，非暴露的子组件简单类名命名方式即可，需要暴露给外部的子组件以 `KL` 开头

比如 [KLTable](https://github.com/kaola-fed/nek-ui/tree/master/src/js/components/layout/KLTable)
