### ISSUE TITLE
kl-upload只在上传成功的时候更新fileList

### ISSUE THREAD

**Issue by LzxHahaha** [kaola-fed/nek-ui#305]
上传失败时的结果不应该放进fileList中，否则会传给后端`blob:xxx`形式的无效url，导致文件丢失

**Comment by ReAlign** [comment]
补充一下：上传失败的，点击右上角删除按钮，只会视觉删除，实际数据仍在fileList中，会影响后续整体操作（上传数量限制受影响）。

![](http://olz3b8fm9.bkt.clouddn.com/18-1-23/14261833.jpg)

**Comment by coldq** [comment]
不管上传是否失败，点击右上角删除按钮，都不会删除父组件里的原有list元素：
[codepen查看console](https://codepen.io/coldq/pen/LJdqLM)

**Comment by LzxHahaha** [comment]
> 不管上传是否失败，点击右上角删除按钮，都不会删除父组件里的原有list元素：
> [codepen查看console](https://codepen.io/coldq/pen/LJdqLM)

删除的时候只会标记被删除元素，方便后端识别哪些是被删除的。可以查看文档的[基本形式](http://nek-ui.kaolafed.com/components/form_KLUpload_.html)部分
