### ISSUE TITLE
ui.button加入防止请求时重复点击的逻辑

### ISSUE THREAD

**Issue by nupthale** [kaola-fed/nek-ui#31]
目前的想法：
1. ui.button里面加个监听器， 外部在request通用的地方，可以在request之前dispatch一个loading的event， request返回后， 再dispatch一个去除loading的event；

2. ui.button和request通过请求的url实现匹配；

**Comment by int64ago** [comment]
2 对组件的侵入性有点大

**Comment by int64ago** [comment]
6e8733d4e720202ccca2c52c098b9d05bccd4425
