### ISSUE TITLE
validationMixin.js 中的bug修复

### ISSUE THREAD

**Issue by ZianeCui** [kaola-fed/nek-ui#323]
validationMixin.js 中 $outer.controls.splice(index, 1);  不会触发 kl-form 中
`this.$watch('this.controls.length', function () {
  this.initSelectorSource();
  this.initFormItem();
});` 的执行

**Comment by ziian-dev** [comment]
https://github.com/kaola-fed/nek-ui/pull/324/commits/b5b2b6ed4a73a1c9dc330570fbd1e5d31e2c2de3
