### ISSUE TITLE
浏览器引用以后怎么跑起来呢

### ISSUE THREAD

**Issue by xmory** [kaola-fed/nek-ui#339]
我是前端菜鸟，以前用过regularjs，现在发现这个项目非常棒，想尝试一下。看见官网的文档是直接使用import语法，好像是要用webpack做吧？如果直接在浏览器中引用js和css，怎么跑起来呢？谢谢。

**Comment by nupthale** [comment]
用script引入，只要nek-ui和regularjs依赖的是同一个regularjs实例，所有组件都可以直接在Regular子类中的模板中直接使用的；例如：
`Regular.extend({ template: "<kl-button>"})`

**Comment by xmory** [comment]
谢谢
