### ISSUE TITLE
[ui.button] 增加导出属性

### ISSUE THREAD

**Issue by int64ago** [kaola-fed/nek-ui#44]
目前 URL 导出文件的两种方式都不太友好：
 - window.open() // 浏览器会拦截
 - location.href = // 页面会被覆盖

因此，为 `ui.button` 增加 export 属性，内部实现是增加一个隐藏的 `<a href={xxx} download style="display:none">download</a>` 链接，导出时设置 href 并且模拟点击

**Comment by nanokind** [comment]
export感觉不如download语义清晰

**Comment by int64ago** [comment]
@fengzilong 也对

**Comment by int64ago** [comment]
656cdbc79aa6f8e07b85bf76821192a2c812bc56
