### ISSUE TITLE
日期选择控件, 选择时分秒后无法自动收起, 失去焦点时也无法自动收起

### ISSUE THREAD

**Issue by yubaoquan** [kaola-fed/nek-ui#55]
希望增加一个确定按钮和取消按钮

**Comment by int64ago** [comment]
你是在文档页尝试的？
https://nek-ui.kaolafed.com/components/form_date.picker_.html

不是很明白你说的“无法自动收起”是什么现象

**Comment by yubaoquan** [comment]
重现不出来了
