### ISSUE TITLE
check.group选项之间会相互影响

### ISSUE THREAD

**Issue by yubaoquan** [kaola-fed/nek-ui#57]
选中一个选项时, 会改变其他选项的选中状态

**Comment by int64ago** [comment]
是文档使用不对，按理 source 的 item 需要有 `key` 和 `nameKey` 字段（默认分别为 `id` 和 `name`）

 > 如果真的没有 `key` ，那么可以设置  `this.data.key = this.data.nameKey`

正确使用已经更新文档
