### ISSUE TITLE
pager增加配置项

### ISSUE THREAD

**Issue by ZianeCui** [kaola-fed/nek-ui#85]
增加配置选项
1、isEllipsis（默认为false） ,值为true时，总条数的展示为后端传的total总数加上+号，如共200条，展示的结果为：共200+条
2、maxTotal，当总条数很多时，如共100000条，可以设置maxTotal的值为1000，展示的结果为：共1000+条

**Comment by ziian-dev** [comment]
c92a984a587a70dc7f6f165ed45b7ac6be473857 @ZianeCui ZianeCui committed 22 seconds ago
