### ISSUE TITLE
NEKUI组件重新命名以及目录结构整理

### ISSUE THREAD

**Issue by nupthale** [kaola-fed/nek-ui#99]
1. 目前组件命名不统一，并且没有命名空间，容易冲突；新的名称都以“kl-”开头；同一个组件，注册两次名称；
2.目录结构整理，有一些不统一的结构，整理统一；

**Comment by int64ago** [comment]
## 结构改动

 - Class 名用驼峰，注册 name 用 `-` 分割
 - 目录名用 Class 名字命名
 - 对外暴露组件 Class 加 `KL` 前缀，注册 name 加 `kl-` 前缀
 - 只供内部使用的子组件，规则同 1，但是**不要加 `KL` `kl-` 前缀**

## 旧组件目录移动

移到 _deprecated_ 目录，移除文档入口，只暴露旧 name 和 Class

 - gotop
 - panel
 - panel.tool
 - select.group
 - suggest
 - tree.select
 - ui.group
 - uploader

## 新旧兼容

 除了新组件 `KLUpload` `KLIcon` `KLCrumb`，其它旧组件全部用新命名方式，并且兼容旧 name 和 Class

## 删除样式

部分样式无法抽离出组件，也没有其它组件依赖，需要删除

 - image

**Comment by int64ago** [comment]
> 子组件分为对内和对外的，对内的没什么好说的，这里讨论对外的

子组件放到父组件文件夹内，需单独暴露，比如：`KLTab` `KLMenuItem` `KLSubMenu` `KLCrumbItem` `KLCardTools` `KLFormItem` `KLTableCol` `KLTableTemplate` 等

> 文档和 JSDoc 注释统一写在父组件内

如果子组件需要验证 `$outer`，需要使用 `this.$outer instanceof KLXxx` 而不是 `this.$outer.name === 'kl-xxx'`，因为 name 验证兼容性不好处理

为了避免循环依赖，只能在子组件内引用父组件，父组件内不可以引用子组件

[KLTable 待修复](https://github.com/kaola-fed/nek-ui/blob/master/src/js/components/layout/KLTable/index.js#L566)

/cc @elcarim5efil

**Comment by int64ago** [comment]
## 不做兼容组件（貌似还没人使用？）

 - MenuSub 
 - MenuItem
 - FormItemTitle - 删除，用属性替代
 - FormItemDescription - 删除，用属性替代

**Comment by int64ago** [comment]
ae3bec3b6268a64cf9e2b5f2c6aada42836ef4c4

**Comment by int64ago** [comment]
不确定 lint 调整：
https://github.com/kaola-fed/nek-ui/blob/beta/src/js/components/layout/ui.table/table.header/index.js#L177

https://github.com/kaola-fed/nek-ui/blob/beta/src/js/components/layout/ui.table/index.js#L141
